name: Semgrep

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: returntocorp/semgrep-action@v1
        with:
          config: >-
            p/default  # Use Semgrep's default open-source security rules

